const encoder=new TextEncoder();
const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store'}});
const parseBody=async request=>{try{return await request.json()}catch{return {}}};
const b64=bytes=>btoa(String.fromCharCode(...bytes)).replaceAll('+','-').replaceAll('/','_').replace(/=+$/,'');
const unb64=value=>Uint8Array.from(atob(value.replaceAll('-','+').replaceAll('_','/')+'==='.slice((value.length+3)%4)),c=>c.charCodeAt(0));
const safeEqual=(a,b)=>a.length===b.length&&a.every((value,index)=>value===b[index]);

async function hashPassword(password){const salt=crypto.getRandomValues(new Uint8Array(16)),iterations=100000 ,key=await crypto.subtle.importKey('raw',encoder.encode(password),'PBKDF2',false,['deriveBits']),hash=new Uint8Array(await crypto.subtle.deriveBits({name:'PBKDF2',hash:'SHA-256',salt,iterations},key,256));return `pbkdf2$${iterations}$${b64(salt)}$${b64(hash)}`}
async function verifyPassword(password,stored=''){const[type,count,saltText,hashText]=stored.split('$');if(type!=='pbkdf2'||!count||!saltText||!hashText)return false;const key=await crypto.subtle.importKey('raw',encoder.encode(password),'PBKDF2',false,['deriveBits']),hash=new Uint8Array(await crypto.subtle.deriveBits({name:'PBKDF2',hash:'SHA-256',salt:unb64(saltText),iterations:Number(count)},key,256));return safeEqual(hash,unb64(hashText))}
async function signSession(userId,secret){const payload=b64(encoder.encode(JSON.stringify({uid:userId,exp:Date.now()+1000*60*60*24*30}))),key=await crypto.subtle.importKey('raw',encoder.encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']),signature=new Uint8Array(await crypto.subtle.sign('HMAC',key,encoder.encode(payload)));return `${payload}.${b64(signature)}`}
async function sessionUser(request,env){const token=request.headers.get('authorization')?.replace(/^Bearer\s+/i,'');if(!token||!env.SESSION_SECRET)return 0;try{const[payload,signature]=token.split('.'),key=await crypto.subtle.importKey('raw',encoder.encode(env.SESSION_SECRET),{name:'HMAC',hash:'SHA-256'},false,['verify']),valid=await crypto.subtle.verify('HMAC',key,unb64(signature),encoder.encode(payload));if(!valid)return 0;const data=JSON.parse(new TextDecoder().decode(unb64(payload)));return data.exp>Date.now()?Number(data.uid):0}catch{return 0}}
const first=(env,sql,...values)=>env.DB.prepare(sql).bind(...values).first();
const all=async(env,sql,...values)=>(await env.DB.prepare(sql).bind(...values).all()).results;
const run=(env,sql,...values)=>env.DB.prepare(sql).bind(...values).run();
const membership=(env,classId,userId)=>first(env,"SELECT * FROM class_members WHERE class_id=? AND user_id=? AND status='accepted'",classId,userId);
const neisDate=value=>value.replaceAll('-','');
async function neisRows(env,service,params={}){const query=new URLSearchParams({Type:'json',pIndex:'1',pSize:'100',...params});if(env.NEIS_API_KEY)query.set('KEY',env.NEIS_API_KEY);const response=await fetch(`https://open.neis.go.kr/hub/${service}?${query}`);if(!response.ok)throw new Error(`나이스 API 요청 실패 (${response.status})`);const data=await response.json(),section=data[service],result=section?.[0]?.head?.find(item=>item.RESULT)?.RESULT;if(result&&result.CODE!=='INFO-000'&&result.CODE!=='INFO-200')throw new Error(result.MESSAGE||'나이스 API 조회 실패');const rows=section?.[1]?.row||[];rows.totalCount=Number(section?.[0]?.head?.find(item=>item.list_total_count)?.list_total_count||rows.length);return rows}
async function findSchool(env,name){const rows=await neisRows(env,'schoolInfo',{SCHUL_NM:name});return rows.find(row=>row.SCHUL_NM===name)||rows[0]||null}
const randomCode=()=>b64(crypto.getRandomValues(new Uint8Array(5))).slice(0,6).toUpperCase();

async function api(request,env){
  const url=new URL(request.url),path=url.pathname,method=request.method,userId=await sessionUser(request,env);let match;
  if(method==='GET'&&path==='/api/auth/check-id')return json({available:!await first(env,'SELECT 1 FROM users WHERE login_id=?',url.searchParams.get('id')||'')});
  if(method==='POST'&&path==='/api/auth/signup'){const data=await parseBody(request),id=String(data.id||'').trim();if(!/^[A-Za-z0-9]{4,20}$/.test(id))return json({error:'아이디는 공백 없이 영문 또는 숫자 4~20자로 입력해 주세요.'},400);if(String(data.password||'').length<8)return json({error:'비밀번호는 8자 이상 입력해 주세요.'},400);if(data.password!==data.passwordConfirm)return json({error:'비밀번호 확인이 일치하지 않습니다.'},400);try{const result=await run(env,'INSERT INTO users(login_id,password_hash,name,email) VALUES(?,?,?,?)',id,await hashPassword(data.password),id,`${id}@mirim.hs.kr`),newId=Number(result.meta.last_row_id);return json({userId:newId,token:await signSession(newId,env.SESSION_SECRET)},201)}catch(error){console.error('SIGNUP ERROR',error);return json({error:'회원가입 처리 중 오류가 발생했습니다.'},500)}
}
  if(method==='POST'&&path==='/api/auth/login'){const data=await parseBody(request),user=await first(env,'SELECT * FROM users WHERE login_id=?',String(data.id||'').trim());if(!user||!await verifyPassword(data.password,user.password_hash))return json({error:'아이디 또는 비밀번호가 올바르지 않습니다.'},401);const member=await first(env,"SELECT class_id classId FROM class_members WHERE user_id=? AND status='accepted' ORDER BY joined_at DESC,id DESC LIMIT 1",user.id);return json({userId:user.id,classId:member?.classId||null,token:await signSession(user.id,env.SESSION_SECRET)})}
  if(!userId)return json({error:'로그인이 필요합니다.'},401);

  if(method==='POST'&&path==='/api/classes'){const data=await parseBody(request),school=await findSchool(env,String(data.schoolName||'').trim());if(!school)return json({error:'나이스에서 학교를 찾을 수 없습니다. 정확한 학교명을 입력해 주세요.'},404);let code=randomCode();while(await first(env,'SELECT 1 FROM classes WHERE invite_code=?',code))code=randomCode();const result=await run(env,'INSERT INTO classes(school_name,school_code,office_code,grade,class_number,invite_code,created_by) VALUES(?,?,?,?,?,?,?)',school.SCHUL_NM,school.SD_SCHUL_CODE,school.ATPT_OFCDC_SC_CODE,Number(data.grade),Number(data.classNum),code,userId),classId=Number(result.meta.last_row_id);await run(env,"INSERT INTO class_members(class_id,user_id,role,status,joined_at) VALUES(?,?,'president','accepted',CURRENT_TIMESTAMP)",classId,userId);return json({classId,inviteCode:code,inviteLink:`/join/${code}`},201)}
  if(method==='POST'&&path==='/api/classes/join'){const data=await parseBody(request),room=await first(env,'SELECT * FROM classes WHERE invite_code=?',String(data.inviteCode||'').toUpperCase());if(!room)return json({error:'일치하는 학급을 찾을 수 없어요.'},404);await run(env,"INSERT INTO class_members(class_id,user_id,role,status,joined_at) VALUES(?,?,'member','accepted',CURRENT_TIMESTAMP) ON CONFLICT(class_id,user_id) DO UPDATE SET status='accepted',joined_at=CURRENT_TIMESTAMP",room.id,userId);return json({classId:room.id,schoolName:room.school_name,grade:room.grade,classNum:room.class_number})}
  if(method==='POST'&&path==='/api/users/me/profile'){const data=await parseBody(request);await run(env,'UPDATE users SET name=? WHERE id=?',String(data.name||'').trim(),userId);return json({ok:true})}

  if((match=path.match(/^\/api\/classes\/(\d+)\/dashboard$/))&&method==='GET'){const classId=Number(match[1]),date=url.searchParams.get('date')||new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Seoul'}).format(new Date());if(userId&&!await membership(env,classId,userId))return json({error:'이 학급에 접근할 권한이 없습니다.'},403);const room=await first(env,'SELECT id,school_name schoolName,school_code schoolCode,office_code officeCode,grade,class_number classNumber FROM classes WHERE id=?',classId);let meal={breakfast:[],lunch:[],dinner:[]},timetable=[],timetableLimited=false,timetableTotal=0;if(room?.schoolCode&&room?.officeCode){try{const common={ATPT_OFCDC_SC_CODE:room.officeCode,SD_SCHUL_CODE:room.schoolCode},mealRequests=['1','2','3'].map(code=>neisRows(env,'mealServiceDietInfo',{...common,MLSV_YMD:neisDate(date),MMEAL_SC_CODE:code})),timeRequest=neisRows(env,'hisTimetable',{...common,ALL_TI_YMD:neisDate(date),GRADE:String(room.grade),CLASS_NM:String(room.classNumber)}),[mealGroups,timeRows]=await Promise.all([Promise.all(mealRequests),timeRequest]),clean=rows=>(rows[0]?.DDISH_NM||'').split(/<br\s*\/?>/i).map(item=>item.replace(/\s*\([\d.]+\)\s*$/,'').replace(/\(j\)/gi,'').replace(/\s{2,}/g,' ').trim()).filter(Boolean);meal={breakfast:clean(mealGroups[0]),lunch:clean(mealGroups[1]),dinner:clean(mealGroups[2])};timetable=timeRows.map(row=>({period:Number(row.PERIO),subject:String(row.ITRT_CNTNT||'').replace(/^\s*\*\s*/,'').trim()})).filter((row,index,rows)=>row.subject&&index===rows.findIndex(item=>item.period===row.period)).sort((a,b)=>a.period-b.period);timetableTotal=timeRows.totalCount||timetable.length;timetableLimited=timetableTotal>timetable.length}catch(error){console.error('NEIS',error)}}const[schedules,notices,supplies]=await Promise.all([all(env,'SELECT id,title,schedule_date date,schedule_time time,type FROM schedules WHERE class_id=? ORDER BY schedule_date,schedule_time LIMIT 100',classId),all(env,"SELECT id,title,content,substr(created_at,6,5) date FROM notices WHERE class_id=? AND category='class' ORDER BY created_at DESC LIMIT 4",classId),all(env,'SELECT id,item,supply_date date FROM supplies WHERE class_id=? AND supply_date>=? ORDER BY supply_date LIMIT 50',classId,date)]);return json({class:room,date,meal,timetable,timetableTotal,timetableLimited,schedules,notices,supplies})}

  if((match=path.match(/^\/api\/classes\/(\d+)\/schedules$/))&&method==='POST'){const classId=Number(match[1]),own=await membership(env,classId,userId),data=await parseBody(request);if(!own)return json({error:'일정 작성 권한이 없습니다.'},403);if(!data.title?.trim()||!/^\d{4}-\d{2}-\d{2}$/.test(data.date||''))return json({error:'일정 제목과 날짜를 확인해 주세요.'},400);const result=await run(env,'INSERT INTO schedules(class_id,title,schedule_date,schedule_time,type) VALUES(?,?,?,?,?)',classId,data.title.trim(),data.date,data.time||null,['class','exam','event'].includes(data.type)?data.type:'class');return json({id:Number(result.meta.last_row_id)},201)}
  if((match=path.match(/^\/api\/classes\/(\d+)\/schedules\/(\d+)$/))){const[classId,id]=match.slice(1).map(Number);if(!await membership(env,classId,userId))return json({error:'일정 관리 권한이 없습니다.'},403);if(method==='PATCH'){const data=await parseBody(request);await run(env,'UPDATE schedules SET title=?,schedule_date=?,schedule_time=?,type=? WHERE id=? AND class_id=?',data.title.trim(),data.date,data.time||null,['class','exam','event'].includes(data.type)?data.type:'class',id,classId);return json({ok:true})}if(method==='DELETE'){await run(env,'DELETE FROM schedules WHERE id=? AND class_id=?',id,classId);return json({ok:true})}}
  if((match=path.match(/^\/api\/classes\/(\d+)\/notices$/))&&method==='POST'){const classId=Number(match[1]),own=await membership(env,classId,userId),data=await parseBody(request);if(!own||!['teacher','president','vice_president'].includes(own.role))return json({error:'공지 작성 권한이 없습니다.'},403);const result=await run(env,"INSERT INTO notices(class_id,category,title,content) VALUES(?,'class',?,?)",classId,data.title.trim(),String(data.content||'').trim());return json({id:Number(result.meta.last_row_id)},201)}
  if((match=path.match(/^\/api\/classes\/(\d+)\/supplies$/))&&method==='POST'){const classId=Number(match[1]),data=await parseBody(request);if(!await membership(env,classId,userId))return json({error:'준비물 추가 권한이 없습니다.'},403);const result=await run(env,'INSERT INTO supplies(class_id,supply_date,item) VALUES(?,?,?)',classId,data.date,data.item.trim());return json({id:Number(result.meta.last_row_id)},201)}
  if((match=path.match(/^\/api\/classes\/(\d+)\/supplies\/(\d+)$/))){const[classId,id]=match.slice(1).map(Number);if(!await membership(env,classId,userId))return json({error:'준비물 관리 권한이 없습니다.'},403);if(method==='PATCH'){const data=await parseBody(request);await run(env,'UPDATE supplies SET item=?,supply_date=? WHERE id=? AND class_id=?',data.item.trim(),data.date,id,classId);return json({ok:true})}if(method==='DELETE'){await run(env,'DELETE FROM supplies WHERE id=? AND class_id=?',id,classId);return json({ok:true})}}

  if((match=path.match(/^\/api\/classes\/(\d+)$/))){const classId=Number(match[1]),own=await membership(env,classId,userId);if(!own)return json({error:'이 학급에 접근할 권한이 없습니다.'},403);if(method==='GET'){const room=await first(env,'SELECT id,school_name schoolName,grade,class_number classNumber,invite_code inviteCode FROM classes WHERE id=?',classId);return room?json(room):json({error:'학급을 찾을 수 없습니다.'},404)}if(method==='PATCH'){if(own.role!=='teacher')return json({error:'선생님만 학급 정보를 수정할 수 있습니다.'},403);const data=await parseBody(request);await run(env,'UPDATE classes SET grade=?,class_number=? WHERE id=?',Number(data.grade),Number(data.classNumber),classId);return json({ok:true})}}
  if((match=path.match(/^\/api\/classes\/(\d+)\/members$/))&&method==='GET'){const classId=Number(match[1]);if(!await membership(env,classId,userId))return json({error:'이 학급에 접근할 권한이 없습니다.'},403);const query=`%${url.searchParams.get('search')||''}%`;return json({members:await all(env,"SELECT cm.id,u.name,u.email,u.profile_image profileImage,cm.role,cm.status FROM class_members cm JOIN users u ON u.id=cm.user_id WHERE cm.class_id=? AND (u.name LIKE ? OR u.email LIKE ?) ORDER BY CASE cm.role WHEN 'teacher' THEN 1 WHEN 'president' THEN 2 WHEN 'vice_president' THEN 3 ELSE 4 END,u.name",classId,query,query)})}
  if((match=path.match(/^\/api\/classes\/(\d+)\/members\/(\d+)\/role$/))&&method==='PATCH'){const[classId,id]=match.slice(1).map(Number),own=await membership(env,classId,userId),data=await parseBody(request);if(!own||!['teacher','president'].includes(own.role)||!['vice_president','member'].includes(data.role))return json({error:'역할을 변경할 권한이 없습니다.'},403);await run(env,"UPDATE class_members SET role=? WHERE id=? AND class_id=? AND role NOT IN('teacher','president')",data.role,id,classId);return json({ok:true})}
  if((match=path.match(/^\/api\/classes\/(\d+)\/members\/(\d+)$/))&&method==='DELETE'){const[classId,id]=match.slice(1).map(Number),own=await membership(env,classId,userId);if(!own||!['teacher','president'].includes(own.role))return json({error:'멤버를 내보낼 권한이 없습니다.'},403);await run(env,"DELETE FROM class_members WHERE id=? AND class_id=? AND role NOT IN('teacher','president')",id,classId);return json({ok:true})}
  if((match=path.match(/^\/api\/classes\/(\d+)\/representatives$/))&&method==='GET'){const classId=Number(match[1]);if(!await membership(env,classId,userId))return json({error:'접근 권한이 없습니다.'},403);const rows=await all(env,"SELECT cm.id,u.name,u.email,u.profile_image profileImage,cm.role,cm.status FROM class_members cm JOIN users u ON u.id=cm.user_id WHERE cm.class_id=? AND cm.role IN('teacher','president','vice_president')",classId),find=role=>rows.find(row=>row.role===role)||null;return json({teacher:find('teacher'),president:find('president'),vicePresident:find('vice_president')})}
  if(path==='/api/me'&&method==='GET'){const user=await first(env,"SELECT u.id,u.name,u.email,u.profile_image profileImage,cm.role FROM users u LEFT JOIN class_members cm ON cm.user_id=u.id AND cm.status='accepted' WHERE u.id=? ORDER BY cm.joined_at DESC LIMIT 1",userId);return json(user)}
  if(path==='/api/me/profile'&&method==='PATCH'){const data=await parseBody(request);if(!data.name?.trim())return json({error:'이름을 입력해 주세요.'},400);await run(env,'UPDATE users SET name=? WHERE id=?',data.name.trim(),userId);return json({ok:true})}
  if(path==='/api/me/password'&&method==='PATCH'){const data=await parseBody(request),user=await first(env,'SELECT * FROM users WHERE id=?',userId);if(!user||!await verifyPassword(data.currentPassword,user.password_hash))return json({error:'현재 비밀번호가 올바르지 않습니다.'},400);if(data.newPassword?.length<8||data.newPassword!==data.confirm)return json({error:'새 비밀번호를 확인해 주세요.'},400);await run(env,'UPDATE users SET password_hash=? WHERE id=?',await hashPassword(data.newPassword),userId);return json({ok:true})}
  return json({error:'API를 찾을 수 없습니다!.'},404);
}

export default {
  async fetch(request, env) {
    console.log("SESSION_SECRET exists:", Boolean(env.SESSION_SECRET));

    try {
      if (new URL(request.url).pathname.startsWith('/api/')) {
        return await api(request, env);
      }

      return env.ASSETS.fetch(request);
    } catch (error) {
      console.error(error);
      return json({ error: '서버 오류가 발생했습니다.' }, 500);
    }
  }
};
