import React from 'react';
import { Trash2, X } from 'lucide-react';

export default function ContentComposer({type,initial,api,classId,onClose,onSaved}){
  const editing=Boolean(initial?.id),today=new Date().toLocaleDateString('en-CA');
  const initialForm=type==='schedule'?{title:initial?.title||'',date:initial?.date||today,time:initial?.time||'',type:initial?.type||'class'}:type==='supply'?{item:initial?.item||'',date:initial?.date||today}:{title:initial?.title||'',content:initial?.content||''};
  const[form,setForm]=React.useState(initialForm),[error,setError]=React.useState(''),[busy,setBusy]=React.useState(false);
  const resource=type==='schedule'?'schedules':type==='supply'?'supplies':'notices';
  async function submit(event){event.preventDefault();if(type==='supply'&&!form.item.trim())return setError('준비물 이름을 입력해 주세요.');if(type!=='supply'&&!form.title.trim())return setError('제목을 입력해 주세요.');if(['schedule','supply'].includes(type)&&!form.date)return setError('날짜를 선택해 주세요.');setBusy(true);setError('');try{const body=type==='supply'?{...form,item:form.item.trim()}:{...form,title:form.title.trim()};await api(`/classes/${classId}/${resource}${editing?`/${initial.id}`:''}`,{method:editing?'PATCH':'POST',body});onSaved()}catch(e){setError(e.message)}finally{setBusy(false)}}
  async function remove(){if(!confirm('정말 삭제할까요?'))return;setBusy(true);try{await api(`/classes/${classId}/${resource}/${initial.id}`,{method:'DELETE'});onSaved()}catch(e){setError(e.message);setBusy(false)}}
  const title=type==='supply'?(editing?'준비물 수정':'준비물 추가'):editing?'일정 수정':type==='schedule'?'일정 추가':'공지 작성';
  return <div className="modal-layer"><button className="modal-backdrop" onClick={onClose}/><section className="modal"><header><h2>{title}</h2><button className="icon-button" onClick={onClose}><X/></button></header><form className="form" onSubmit={submit}>{type==='supply'?<><label>준비물<input value={form.item} onChange={e=>setForm({...form,item:e.target.value})} placeholder="준비물 이름" autoFocus/></label><label>필요한 날짜<input type="date" value={form.date} onChange={e=>setForm({...form,date:e.target.value})}/></label></>:<><label>제목<input value={form.title} onChange={e=>setForm({...form,title:e.target.value})} autoFocus/></label>{type==='schedule'?<><div className="form-grid"><label>날짜<input type="date" value={form.date} onChange={e=>setForm({...form,date:e.target.value})}/></label><label>시간<input type="time" value={form.time} onChange={e=>setForm({...form,time:e.target.value})}/></label></div><label>유형<select value={form.type} onChange={e=>setForm({...form,type:e.target.value})}><option value="class">학급 일정</option><option value="exam">시험</option><option value="event">행사</option></select></label></>:<label>내용<textarea rows="6" value={form.content} onChange={e=>setForm({...form,content:e.target.value})}/></label>}</>}{error&&<p className="form-error">{error}</p>}<div className="modal-actions">{editing&&<button type="button" className="danger-button" onClick={remove}><Trash2/>삭제</button>}<button type="button" className="secondary-button" onClick={onClose}>취소</button><button className="primary-button" disabled={busy}>{busy?'저장 중...':'저장'}</button></div></form></section></div>}
